# Generated by Django 5.2.7 on 2025-11-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_op_search_document', models.CharField(max_length=255, unique=True)),
                ('index_name', models.CharField(default='default_document', max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('id_document', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
